import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { inventory } from "@/data/inventory";
import { useState } from "react";
import { useEffect } from "react";
import Product from "@/components/Product";

export default function Home() {
  const [products, setProducts] = useState([...inventory.clothing]);
  const [selectedCategory, setSelectedCategory] = useState("");
  const [selectedSex, setSelectedSex] = useState("");

  return (
    <>
      <Head>
        <title>Assignment02 - Aaron Tripp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.sectionHead}>Filter By</h1>
        <div className={styles.productContainer}>
          {products &&
            products.map((item, index) => (
              <Product
                key={index}
                img={item.image}
                tag={<span className={styles.productTitle}>{item.title}</span>}
                price={<span className={styles.productPrice}>{item.cost}</span>}
              />
            ))}
        </div>
      </main>
    </>
  );
}
