import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { inventory } from "@/data/inventory";
import { useState } from "react";
import { useEffect } from "react";
import Product from "@/components/Product";
import Filter from "@/components/Filter";

export default function Home() {
  const [products, setProducts] = useState(inventory.clothing);

  const updateProducts = (category, sex) => {
    let newProducts = [];
    if (category === "All" && sex === "All") {
      newProducts = inventory.clothing;
    } else if (category === "All") {
      newProducts = inventory.clothing.filter((product) => product.sex === sex);
    } else if (sex === "All") {
      newProducts = inventory.clothing.filter(
        (product) => product.category === category
      );
    } else {
      newProducts = inventory.clothing.filter(
        (product) => product.category === category && product.sex === sex
      );
    }
    setProducts(newProducts);
  };

  return (
    <>
      <Head>
        <title>Assignment02 - Aaron Tripp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image src="/logo/logo.png" objectFit="cover" width="250" height="38" />
      <div className={styles.headerLine}></div>

      <main className={styles.main}>
        <h1 className={styles.sectionHead}>Filter By</h1>
        <Filter setProducts={setProducts} updateProducts={updateProducts} />
        <div className={styles.productContainer}>
          {products &&
            products.map((item, index) => (
              <Product
                key={index}
                img={item.image}
                tag={<span className={styles.productTitle}>{item.title}</span>}
                price={<span className={styles.productPrice}>{item.cost}</span>}
              />
            ))}
        </div>
      </main>
    </>
  );
}
